# Generated by Django 6.0.2 on 2026-02-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward: Rename contacts_contact to athletes_athlete
            sql="ALTER TABLE contacts_contact RENAME TO athletes_athlete;",
            # Reverse: Rename athletes_athlete back to contacts_contact
            reverse_sql="ALTER TABLE athletes_athlete RENAME TO contacts_contact;",
        ),
        # Update contenttypes to reflect the app/model rename
        migrations.RunSQL(
            sql="""
                UPDATE django_content_type 
                SET app_label = 'athletes', model = 'athlete' 
                WHERE app_label = 'contacts' AND model = 'contact';
            """,
            reverse_sql="""
                UPDATE django_content_type 
                SET app_label = 'contacts', model = 'contact' 
                WHERE app_label = 'athletes' AND model = 'athlete';
            """,
        ),
    ]
