# Generated by Django 6.0.2 on 2026-02-06 18:47

from django.db import migrations, connection


def rename_table_if_exists(apps, schema_editor):
    """Rename contacts_contact to athletes_athlete if the table exists."""
    with connection.cursor() as cursor:
        # Check if contacts_contact table exists
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='contacts_contact'
        """)
        if cursor.fetchone():
            # Table exists, rename it
            cursor.execute("ALTER TABLE contacts_contact RENAME TO athletes_athlete;")


def reverse_rename_table(apps, schema_editor):
    """Reverse: Rename athletes_athlete back to contacts_contact if it exists."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='athletes_athlete'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE athletes_athlete RENAME TO contacts_contact;")


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(
            rename_table_if_exists,
            reverse_rename_table,
        ),
        # Update contenttypes to reflect the app/model rename
        migrations.RunSQL(
            sql="""
                UPDATE django_content_type 
                SET app_label = 'athletes', model = 'athlete' 
                WHERE app_label = 'contacts' AND model = 'contact';
            """,
            reverse_sql="""
                UPDATE django_content_type 
                SET app_label = 'contacts', model = 'contact' 
                WHERE app_label = 'athletes' AND model = 'athlete';
            """,
        ),
    ]
