# Generated by Django 6.0.2 on 2026-02-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_rename_contact_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='email',
        ),
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='height',
            field=models.CharField(blank=True, help_text='Height (e.g., 5\'10" or 178cm)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in pounds (lbs)', max_digits=5, null=True),
        ),
    ]
